name: Say hello

on:
  push:
    branches:
      - main      

jobs:
  hello_world:
    runs-on: ubunto-latest
    steps:
      - name: Echo the message
        run: |
          echo "Hola Nico!"
      - name: Dime la fecha
        run: date 
      - run: ls -l   